
package com.company.module.model;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

@Entity
@Table(name = "MnjBomBpoLinesAll")
@Getter
@Setter
@Slf4j
public class BomBpoLinesAllVORowImpl {

    @Id
    @GeneratedValue
    private Long id; // Assuming a primary key field

    private Number bomId;
    private String bpoNo;
    private String endUserDesc;
    private String fit;
    private Number lineId;
    private Number orderQty;
    private Number saleOrderId;
    private String userItemDesc;
    private String brand;
    private String styleNo;
    private String season;
    private Number totOrdQty;
    private BigDecimal totalOrderQty;
    private String category;

    @Autowired
    private BomBpoLinesAllRepository repository; // Assuming a repository for data access

    public BigDecimal calculateTotalOrderQty() {
        BigDecimal total = BigDecimal.ZERO;
        List<BomBpoLinesAllVORowImpl> rows = repository.findAll(); // Fetch all rows

        for (BomBpoLinesAllVORowImpl row : rows) {
            BigDecimal rowValue = row.getOrderQty() != null ? new BigDecimal(row.getOrderQty().doubleValue()) : BigDecimal.ZERO;
            total = total.add(rowValue);
            log.info("Level Total: {} {}", rowValue, total);
        }

        return total;
    }

    // Other getters and setters are generated by Lombok
}
